// <auto-generated by scripts/generate-lle-nid-registrations.py />
// Copyright (C) 2026 SharpEmu Emulator Project
// SPDX-License-Identifier: GPL-2.0-or-later
//
// Ghidra 12.1.2 program: libSceContentDelete.sprx
// Analyzed provider SHA-256: 0ad321f0f820ce2a08227a2bcf2050bc8abe349c63a7d71d1b7d1ef02d92e77c
// Each registration prefers the loaded guest export. The shared HLE handler
// is deliberately fail-closed and never claims provider behavior.

using SharpEmu.HLE;

namespace SharpEmu.Libs.Lle;

public static class ContentDeleteLleExports
{
    // Ghidra entry 00000650; body addresses 66.
    [SysAbiExport(
        Nid = "5XLSih32qHA",
        ExportName = "sceContentDeleteTerminate",
        Target = Generation.Gen5,
        LibraryName = "libSceContentDelete",
        PreferLle = true)]
    // Ghidra entry 000007a0; body addresses 458.
    [SysAbiExport(
        Nid = "qC3QW+AltHs",
        ExportName = "sceContentDeleteByPath",
        Target = Generation.Gen5,
        LibraryName = "libSceContentDelete",
        PreferLle = true)]
    // Ghidra entry 000005d0; body addresses 120.
    [SysAbiExport(
        Nid = "zoxb0wEChEM",
        ExportName = "sceContentDeleteInitialize",
        Target = Generation.Gen5,
        LibraryName = "libSceContentDelete",
        PreferLle = true)]
    public static int MissingGuestProvider(CpuContext ctx)
    {
        if (string.Equals(Environment.GetEnvironmentVariable("SHARPEMU_LOG_IMPORTS"), "1", StringComparison.Ordinal))
        {
            Console.Error.WriteLine("[LOADER][ERROR] ContentDelete LLE-preferred export reached its fail-closed HLE fallback");
        }

        return ctx.SetReturn(OrbisGen2Result.ORBIS_GEN2_ERROR_NOT_IMPLEMENTED);
    }
}
