// <auto-generated by scripts/generate-lle-nid-registrations.py />
// Copyright (C) 2026 SharpEmu Emulator Project
// SPDX-License-Identifier: GPL-2.0-or-later
//
// Ghidra 12.1.2 program: libSceContentSearch.sprx
// Analyzed provider SHA-256: ce2ecc3765d0228fac6808b5a425b8d77ffae5b6b99c73ee3313d8ac22cfadb8
// Each registration prefers the loaded guest export. The shared HLE handler
// is deliberately fail-closed and never claims provider behavior.

using SharpEmu.HLE;

namespace SharpEmu.Libs.Lle;

public static class ContentSearchLleExports
{
    // Ghidra entry 0001e760; body addresses 217.
    [SysAbiExport(
        Nid = "-YbpaF0XS-I",
        ExportName = "sceContentSearchCloseMetadata",
        Target = Generation.Gen5,
        LibraryName = "libSceContentSearch",
        PreferLle = true)]
    // Ghidra entry 0001d600; body addresses 560.
    [SysAbiExport(
        Nid = "1xSZodB2geA",
        ExportName = "sceContentSearchTerm",
        Target = Generation.Gen5,
        LibraryName = "libSceContentSearch",
        PreferLle = true)]
    // Ghidra entry 0001e840; body addresses 326.
    [SysAbiExport(
        Nid = "EbNufIY0Zvc",
        ExportName = "sceContentSearchGetMetadataFieldInfo",
        Target = Generation.Gen5,
        LibraryName = "libSceContentSearch",
        PreferLle = true)]
    // Ghidra entry 0001e550; body addresses 262.
    [SysAbiExport(
        Nid = "G13HF1z-e4o",
        ExportName = "sceContentSearchOpenMetadata",
        Target = Generation.Gen5,
        LibraryName = "libSceContentSearch",
        PreferLle = true)]
    // Ghidra entry 0001dc00; body addresses 429.
    [SysAbiExport(
        Nid = "TEW3IKxYfXc",
        ExportName = "sceContentSearchSearchContent",
        Target = Generation.Gen5,
        LibraryName = "libSceContentSearch",
        PreferLle = true)]
    // Ghidra entry 0001d2e0; body addresses 800.
    [SysAbiExport(
        Nid = "dPj4ZtRcIWk",
        ExportName = "sceContentSearchInit",
        Target = Generation.Gen5,
        LibraryName = "libSceContentSearch",
        PreferLle = true)]
    // Ghidra entry 0001e990; body addresses 302.
    [SysAbiExport(
        Nid = "ruNe-FgCzO8",
        ExportName = "sceContentSearchGetMetadataValue",
        Target = Generation.Gen5,
        LibraryName = "libSceContentSearch",
        PreferLle = true)]
    public static int MissingGuestProvider(CpuContext ctx)
    {
        if (string.Equals(Environment.GetEnvironmentVariable("SHARPEMU_LOG_IMPORTS"), "1", StringComparison.Ordinal))
        {
            Console.Error.WriteLine("[LOADER][ERROR] ContentSearch LLE-preferred export reached its fail-closed HLE fallback");
        }

        return ctx.SetReturn(OrbisGen2Result.ORBIS_GEN2_ERROR_NOT_IMPLEMENTED);
    }
}
