// <auto-generated by scripts/generate-lle-nid-registrations.py />
// Copyright (C) 2026 SharpEmu Emulator Project
// SPDX-License-Identifier: GPL-2.0-or-later
//
// Ghidra 12.1.2_PUBLIC_20260605 program: libSceGameLiveStreaming.sprx
// Analyzed provider SHA-256: 93b31789fc637b0fa3f4c7fd9364f21130958583bfb10c717c222dac9fc3c369
// Each registration prefers the loaded guest export. The shared HLE handler
// is deliberately fail-closed and never claims provider behavior.

using SharpEmu.HLE;

namespace SharpEmu.Libs.Lle;

public static class GameLiveStreamingLleExports
{
    // Ghidra entry 00001340; body addresses 140.
    [SysAbiExport(
        Nid = "9yK6Fk8mKOQ",
        ExportName = "sceGameLiveStreamingTerminate",
        Target = Generation.Gen5,
        LibraryName = "libSceGameLiveStreaming",
        PreferLle = true)]
    // Ghidra entry 000013e0; body addresses 488.
    [SysAbiExport(
        Nid = "kvYEw2lBndk",
        ExportName = "sceGameLiveStreamingInitialize",
        Target = Generation.Gen5,
        LibraryName = "libSceGameLiveStreaming",
        PreferLle = true)]
    public static int InitializeWithoutGuestProvider(CpuContext ctx)
    {
        // The Ghidra-recovered provider requires a 0x4000-byte pool. With a
        // valid pool request but no live-streaming service, it returns the
        // provider's deterministic unavailable result without creating state.
        return ctx[CpuRegister.Rdi] == 0x4000
            ? ctx.SetReturn(unchecked((int)0x80A00007))
            : ctx.SetReturn(unchecked((int)0x80A00002));
    }

    public static int MissingGuestProvider(CpuContext ctx)
    {
        if (string.Equals(Environment.GetEnvironmentVariable("SHARPEMU_LOG_IMPORTS"), "1", StringComparison.Ordinal))
        {
            Console.Error.WriteLine("[LOADER][ERROR] GameLiveStreaming LLE-preferred export reached its fail-closed HLE fallback");
        }

        return ctx.SetReturn(OrbisGen2Result.ORBIS_GEN2_ERROR_NOT_IMPLEMENTED);
    }
}
