// <auto-generated by scripts/generate-lle-nid-registrations.py />
// Copyright (C) 2026 SharpEmu Emulator Project
// SPDX-License-Identifier: GPL-2.0-or-later
//
// Ghidra 12.1.2_PUBLIC_20260605 program: libSceSaveData.native.sprx
// Analyzed provider SHA-256: d07ff61fa98adff1f0bdde7f1df03d33133e932a9da82ce1005d4784bc948755
// Each registration prefers the loaded guest export. The shared HLE handler
// is deliberately fail-closed and never claims provider behavior.

using SharpEmu.HLE;

namespace SharpEmu.Libs.Lle;

public static class SaveDataNativeLleExports
{
    // Ghidra entry 00027100; body addresses 382.
    [SysAbiExport(
        Nid = "S1GkePI17zQ",
        ExportName = "sceSaveDataDelete",
        Target = Generation.Gen5,
        LibraryName = "libSceSaveData_native",
        PreferLle = true)]
    // Ghidra entry 00028240; body addresses 291.
    [SysAbiExport(
        Nid = "Z7z6HXWORJY",
        ExportName = "sceSaveDataSaveIconByPath",
        Target = Generation.Gen5,
        LibraryName = "libSceSaveData_native",
        PreferLle = true)]
    // Ghidra entry 00026320; body addresses 434.
    [SysAbiExport(
        Nid = "yKDy8S5yLA0",
        ExportName = "sceSaveDataTerminate",
        Target = Generation.Gen5,
        LibraryName = "libSceSaveData_native",
        PreferLle = true)]
    public static int MissingGuestProvider(CpuContext ctx)
    {
        if (string.Equals(Environment.GetEnvironmentVariable("SHARPEMU_LOG_IMPORTS"), "1", StringComparison.Ordinal))
        {
            Console.Error.WriteLine("[LOADER][ERROR] SaveData_native LLE-preferred export reached its fail-closed HLE fallback");
        }

        return ctx.SetReturn(OrbisGen2Result.ORBIS_GEN2_ERROR_NOT_IMPLEMENTED);
    }
}
