// <auto-generated by scripts/generate-lle-nid-registrations.py />
// Copyright (C) 2026 SharpEmu Emulator Project
// SPDX-License-Identifier: GPL-2.0-or-later
//
// Ghidra 12.1.2_PUBLIC_20260605 program: libSceSharePlay.sprx
// Analyzed provider SHA-256: d41598603a31066e405fb2f60e5d848b36d12b0b109c3862f8d5eba93ae0ddb4
// Each registration prefers the loaded guest export. The shared HLE handler
// is deliberately fail-closed and never claims provider behavior.

using SharpEmu.HLE;

namespace SharpEmu.Libs.Lle;

public static class SharePlayLleExports
{
    // Ghidra entry 00000a90; body addresses 18.
    [SysAbiExport(
        Nid = "UaLjloJinow",
        ExportName = "sceSharePlayTerminate",
        Target = Generation.Gen5,
        LibraryName = "libSceSharePlay",
        PreferLle = true)]
    // Ghidra entry 00000a60; body addresses 36.
    [SysAbiExport(
        Nid = "isruqthpYcw",
        ExportName = "sceSharePlayInitialize",
        Target = Generation.Gen5,
        LibraryName = "libSceSharePlay",
        PreferLle = true)]
    public static int MissingGuestProvider(CpuContext ctx)
    {
        if (string.Equals(Environment.GetEnvironmentVariable("SHARPEMU_LOG_IMPORTS"), "1", StringComparison.Ordinal))
        {
            Console.Error.WriteLine("[LOADER][ERROR] SharePlay LLE-preferred export reached its fail-closed HLE fallback");
        }

        return ctx.SetReturn(OrbisGen2Result.ORBIS_GEN2_ERROR_NOT_IMPLEMENTED);
    }
}
