// <auto-generated by scripts/generate-lle-nid-registrations.py />
// Copyright (C) 2026 SharpEmu Emulator Project
// SPDX-License-Identifier: GPL-2.0-or-later
//
// Ghidra 12.1.2_PUBLIC_20260605 program: libSceVoice.sprx
// Analyzed provider SHA-256: bacd6c18bde775e27eade58f33460c86a7cad68b5c2716ce12b6bec8bd138df3
// Each registration prefers the loaded guest export. The shared HLE handler
// is deliberately fail-closed and never claims provider behavior.

using SharpEmu.HLE;

namespace SharpEmu.Libs.Lle;

public static class VoiceLleExports
{
    // Ghidra entry 00017bf0; body addresses 165.
    [SysAbiExport(
        Nid = "54phPH2LZls",
        ExportName = "sceVoiceStart",
        Target = Generation.Gen5,
        LibraryName = "libSceVoice",
        PreferLle = true)]
    // Ghidra entry 00017a90; body addresses 167.
    [SysAbiExport(
        Nid = "9TrhuGzberQ",
        ExportName = "sceVoiceInit",
        Target = Generation.Gen5,
        LibraryName = "libSceVoice",
        PreferLle = true)]
    // Ghidra entry 00017ca0; body addresses 132.
    [SysAbiExport(
        Nid = "Ao2YNSA7-Qo",
        ExportName = "sceVoiceStop",
        Target = Generation.Gen5,
        LibraryName = "libSceVoice",
        PreferLle = true)]
    // Ghidra entry 00019970; body addresses 83.
    [SysAbiExport(
        Nid = "CrLqDwWLoXM",
        ExportName = "sceVoiceGetPortInfo",
        Target = Generation.Gen5,
        LibraryName = "libSceVoice",
        PreferLle = true)]
    // Ghidra entry 00017b40; body addresses 161.
    [SysAbiExport(
        Nid = "Oo0S5PH7FIQ",
        ExportName = "sceVoiceEnd",
        Target = Generation.Gen5,
        LibraryName = "libSceVoice",
        PreferLle = true)]
    // Ghidra entry 00018650; body addresses 196.
    [SysAbiExport(
        Nid = "QBFoAIjJoXQ",
        ExportName = "sceVoiceSetVolume",
        Target = Generation.Gen5,
        LibraryName = "libSceVoice",
        PreferLle = true)]
    // Ghidra entry 000198e0; body addresses 71.
    [SysAbiExport(
        Nid = "YeJl6yDlhW0",
        ExportName = "sceVoiceWriteToIPort",
        Target = Generation.Gen5,
        LibraryName = "libSceVoice",
        PreferLle = true)]
    // Ghidra entry 00019790; body addresses 168.
    [SysAbiExport(
        Nid = "ajVj3QG2um4",
        ExportName = "sceVoiceDisconnectIPortFromOPort",
        Target = Generation.Gen5,
        LibraryName = "libSceVoice",
        PreferLle = true)]
    // Ghidra entry 00019840; body addresses 149.
    [SysAbiExport(
        Nid = "b7kJI+nx2hg",
        ExportName = "sceVoiceDeletePort",
        Target = Generation.Gen5,
        LibraryName = "libSceVoice",
        PreferLle = true)]
    // Ghidra entry 00018890; body addresses 184.
    [SysAbiExport(
        Nid = "cJLufzou6bc",
        ExportName = "sceVoiceGetBitRate",
        Target = Generation.Gen5,
        LibraryName = "libSceVoice",
        PreferLle = true)]
    // Ghidra entry 00019930; body addresses 64.
    [SysAbiExport(
        Nid = "cQ6DGsQEjV4",
        ExportName = "sceVoiceReadFromOPort",
        Target = Generation.Gen5,
        LibraryName = "libSceVoice",
        PreferLle = true)]
    // Ghidra entry 00017e60; body addresses 151.
    [SysAbiExport(
        Nid = "clyKUyi3RYU",
        ExportName = "sceVoiceSetThreadsParams",
        Target = Generation.Gen5,
        LibraryName = "libSceVoice",
        PreferLle = true)]
    // Ghidra entry 00018a10; body addresses 338.
    [SysAbiExport(
        Nid = "elcxZTEfHZM",
        ExportName = "sceVoiceGetPortAttr",
        Target = Generation.Gen5,
        LibraryName = "libSceVoice",
        PreferLle = true)]
    // Ghidra entry 00019560; body addresses 185.
    [SysAbiExport(
        Nid = "nXpje5yNpaE",
        ExportName = "sceVoiceCreatePort",
        Target = Generation.Gen5,
        LibraryName = "libSceVoice",
        PreferLle = true)]
    // Ghidra entry 000196e0; body addresses 168.
    [SysAbiExport(
        Nid = "oV9GAdJ23Gw",
        ExportName = "sceVoiceConnectIPortToOPort",
        Target = Generation.Gen5,
        LibraryName = "libSceVoice",
        PreferLle = true)]
    public static int MissingGuestProvider(CpuContext ctx)
    {
        if (string.Equals(Environment.GetEnvironmentVariable("SHARPEMU_LOG_IMPORTS"), "1", StringComparison.Ordinal))
        {
            Console.Error.WriteLine("[LOADER][ERROR] Voice LLE-preferred export reached its fail-closed HLE fallback");
        }

        return ctx.SetReturn(OrbisGen2Result.ORBIS_GEN2_ERROR_NOT_IMPLEMENTED);
    }
}
